import re
from typing import Dict, List, Any, Generator, Tuple
import json
from observabilty.logger import get_logger, log_error
from services.openai import get_openai_client

logger = get_logger(__name__)

def get_acronym_lookup(text: str, model: str = "gpt-3.5-turbo") -> List[Dict[str, Any]]:
    """
    Takes a generic formatted block of acronyms common to many text docments and returns a dictionary lookup table.
    """
    # get non-empty lines
    clean_lines = [line.strip() for line in text.splitlines() if line.strip()]

    # instructions = """
    # You are a specialized data processor. The content is a text document and your job is to detect lines that start with abbreviations and detect the expanded meaning of the abbreviation.
    # Look for abbreviations indicating speakers, places, sites and acronyms all of which may be in separate tables throughout the document.
    # The abbreviation will appear in a table of sequential lines of the text where the abbreviation is the first part of the line, and the remainder of the line is the definition.
    # Extract these abbreviations and associated definitions to produce a single well formed JSON object with the abbreviations as the object keys and the acronym definitions as the associated values. 
    # 
    # """
    instructions = """
You are a specialized data processor. You evaluate document content for the purpose of extracting definitions of acryonyms and abbreviation from NASA documents.
Identify abbreviations by looking for words apearing in all capitalized letters at the start of a line, followed by a series of spaces leading to the assocaited definition.
Pay close attention to lines that include a human name and ensure the human name is included as part of the definition.
Produce a JSON object with the abbreviation as the field name of the object and the definition text as the string value for that field.
The result must be well formed JSON with no other text formatting or markup.
"""

    system_prompt = {
        "role": "system", 
        "content": instructions
    }

    user_prompt = {
            "role": "user",
            "content": "\n".join(clean_lines)
    }

    logger.debug(f"USER_PROMPT: {user_prompt}")
    try:
        openai_client = get_openai_client()
        response = openai_client.chat.completions.create(
            model=model,
            messages=[system_prompt, user_prompt],
            temperature=0 # we want predictable consistent json objects
        )

        content = response.choices[0].message.content

        logger.debug(f"ACRONYM CONTENT: {content}")

        json_data = json.loads(content)

        # remove unwanted characters like periods from the values
        cleaned_data = {k: v.replace('.', '') for k, v in json_data.items()}

        return cleaned_data
    except Exception as e:
        log_error(logger, f'Failed to extract acronyms from text: {e}', e)
        raise

class AcronymExpander:
    """Helper class to enrich the transcript data with acronym definitions, generated by Gemini AI with my guidance."""

    def __init__(self, acronym_mapping: dict):
        """
        Initializes the expander with a dictionary of acronyms.
        Example: {"LMP": "Lunar Module Pilot"}
        """
        self.mapping = acronym_mapping
        # Compile a regex pattern that matches any of the keys as whole words
        # This is more efficient than iterating the dict for every line
        self._pattern = re.compile(
            r'\b(' + '|'.join(re.escape(key) for key in acronym_mapping.keys()) + r')\b'
        )

    def _replace_match(self, match):
        """Helper to return the original + the expansion."""
        word = match.group(0)
        expansion = self.mapping.get(word)
        return f"{word} ({expansion})"

    def filter_related_acronyms(self, text: dict):
        """Extracts acronyms and definitions found in the text and returns them in a dictionary"""
        # findall returns a unique list of all matches. 
        found_keys = set(self._pattern.findall(text))
        
        # Return only the subset of the mapping that exists in the text
        return {key: self.mapping[key] for key in found_keys if key in self.mapping}

    def process_text(self, text: str) -> str:
        """
        Scans text for acronyms and returns the augmented version.
        """
        if not self.mapping:
            return text
        return self._pattern.sub(self._replace_match, text)
    
class TranscriptProcessor:
    """
    Processing tools for parsing and transforming text transcripts with timestamps and speakers.
    """
    def __init__(self):
        # Our regex from before, optimized for performance
        self.pattern = re.compile(
            r"(?P<timestamp>\d{3}:\d{2}:\d{2})\s+(?P<speaker>[A-Z]{2,4})\n(?P<content>.*?)(?=\n\d{3}:\d{2}:\d{2}|$)",
            re.DOTALL
        )

    def process_transcript(self, raw_text: str, metadata: Dict[str, Any], acronym_expander) -> Generator[Dict[str, Any], None, None]:
        """
        A generator that yields a processed record one at a time.
        """
        count = 0
        for match in self.pattern.finditer(raw_text):
            count += 1
            timestamp = match.group("timestamp")
            speaker = match.group("speaker")
            content = match.group("content").strip()
            
            # Enrich the text for the Vector Embedding
            # We enrich both the speaker acronym and the body content
            enriched_speaker = acronym_expander.process_text(speaker)
            enriched_content = acronym_expander.process_text(content)

            yield {
                "enriched_text": f"[{timestamp} {enriched_speaker}]: {enriched_content}",
                "metadata": metadata | {
                    "timestamp": timestamp,
                    "speaker_raw": speaker,
                    "speaker_full": enriched_speaker,
                    "original_text": f"{timestamp} {speaker}: {content}",
                }
            }

    def parse_transcript_sections(self, raw_text: str) -> Tuple[str]:
        """
        Break up the document into standard sections for a mission transcript.

        Returns:
            Tuple(title page, introduction, acronym_list, transcript log)
        """
        # Pattern to find our specific section markers
        markers = r'(INTRODUCTION|ACRONYM LIST|\d{3}:\d{2}:\d{2})'
        
        # Split the text
        parts = re.split(markers, raw_text)
        
        # parts[0] is everything before 'INTRODUCTION'
        title_page = parts[0].strip()
        
        # Initialize containers
        acronym_text = ""
        introduction_text = ""
        transcript_text = ""
        
        # Iterate through the list to find our anchors
        for i in range(len(parts)):
            if parts[i] == "INTRODUCTION":
                # The content follows the marker in the split list
                introduction_text = parts[i+1].strip()
            elif parts[i] == "ACRONYM LIST":
                acronym_text = parts[i+1].strip()
            elif re.match(r'\d{3}:\d{2}:\d{2}', parts[i]):
                # Once we hit the first timestamp, we grab everything left
                # Join the remaining parts back together to preserve the log
                transcript_text = "".join(parts[i:])
                break 
                
        return title_page, introduction_text, acronym_text, transcript_text



            